I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'renpy/common/000atl.rpy', 1631219226, 13) is defined twice, at renpy/common/000atl.rpy:25 and renpy/common/000atl.rpy:25.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 482, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "renpy/script.py", line 283, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "renpy/script.py", line 797, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn)
  File "renpy/script.py", line 473, in finish_load
    check_name(node)
  File "renpy/script.py", line 452, in check_name
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'renpy/common/000atl.rpy', 1631219226, 13) is defined twice, at renpy/common/000atl.rpy:25 and renpy/common/000atl.rpy:25.

Windows-10-10.0.19041
Ren'Py 7.4.9.2142
 
Sun Jan 15 18:10:24 2023
